#!/bin/sh

set -e

lang="opa"
lang_version="$1"

if [ "$lang_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t ${lang}_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# build and package for heroku
touch nothing
vulcan build -p /app/mlstate-opa -c "curl -L -o run http://download.opalang.org/linux/opa_1.0s3.5%2Bbuild${lang_version}_amd64.run && chmod +x run && ./run -- /app/mlstate-opa" -o $tempdir/${lang}-${lang_version}.tgz -v

# upload to s3
$basedir/aws/s3 put $S3_BUCKET \
  ${lang}-${lang_version}.tgz $tempdir/${lang}-${lang_version}.tgz
